tasks/urls.py
from django.contrib import admin 
from django.urls import path 
from tasks import views

urlpatterns = [
    path("", views.index, name = 'index'),
    path("update_task/<int:myid>", views.update_task, name="update_task"),
    path("delete_task/<int:myid>", views.delete_task, name="delete_task"),
]

todoapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tasks.urls')),
]

tasks/models.py
from django.db import models

# Create your models here.
class Task(models.Model):
    title = models.CharField( max_length=50)
    complete = models.BooleanField(default = False)
    created = models.DateTimeField(auto_now_add = True) #Added automatically each time an object is created

    
    def __str__(self):
        return self.title
    

tasks/forms.py
from django import forms
from django.forms import ModelForm 

from tasks.models import Task

class TaskForm(forms.ModelForm):  #Type ModelForm for shortcut
    
    class Meta:
        model = Task #Same name as the model we want to create the form for
        fields = '__all__' #Allow all fields

tasks/views.py
from django.shortcuts import render, redirect
from tasks.models import Task
from .forms import *
# Create your views here.


def index(request):

    # For adding a new task
    form = TaskForm()
    if request.method == 'POST':
        form = TaskForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/')

    # For rendering the tasks on the page
    all_tasks = Task.objects.all()
    params = {'all_tasks': all_tasks, 'form': form}
    return render(request, 'index.html', params)


def update_task(request, myid):
    task = Task.objects.get(id=myid)
    # if you just pass TaskForm it will give a blank form
    form = TaskForm(instance=task)
    # Because instance = task is given, it will be pre-filled with that task

    params = {'form': form}
    if request.method == 'POST':
        form = TaskForm(request.POST, instance=task)#Here instance is required again because
                                                      #if we dont do so, it will create a new item instead of updatig it
                                                      #We are saying that we are giving in new data but still updating
                                                      #the insatnce of the old item
        if form.is_valid():
            form.save()
            return redirect('/')
    return render(request, 'update_task.html', params)

def delete_task(request, myid):
    task = Task.objects.get(id = myid)
    params = {'task':task} #Required for rendering the data

    if request.method == 'POST':
        task.delete()
        return redirect('/')
    return render(request, 'delete_task.html', params)

tasks/templates/delete_task.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Cabin:ital,wght@0,400;1,600&family=Noto+Sans+SC:wght@100;400;700&display=swap" rel="stylesheet">
    <title>Delete | To Do App</title>
</head>
<style>
    *,
    *::after,
    *::before {
        box-sizing: border-box;
        text-decoration: none;
        margin: 0;
        padding: 0;
        font-family: 'Noto Sans SC', sans-serif;
        font-weight: 400;
    }
    
    html {
        font-size: 100%;
    }
    
     :root {
        --mainbg: rgb(241, 209, 209);
        --buttonbg: rgb(247, 152, 152);
    }
    
    .container {
        display: flex;
        justify-content: center;
        align-items: center;
        flex-direction: column;
        margin: 2rem;
        /* width: 100%;
            box-sizing: border-box; */
    }
    
    .container h2 {
        font-size: 2rem;
        /* align-items: center; */
        align-self: center;
        margin-bottom: 2rem;
        text-align: center;
    }
    
    .container h2 b {
        font-weight: 600;
    }
    
    .button {
        all: unset;
        cursor: pointer;
        display: inline-block;
        width: 8rem;
        padding: 0.4rem 0.3rem;
        margin: 0.4rem 0.3rem;
        text-align: center;
        /* border: 2px solid green; */
        border-radius: 6px;
        text-decoration: none;
        background-color: var(--buttonbg);
        color: white;
        border: none;
    }
</style>

<body>
    <div class="container">
        <h2>Are you sure you want to delete </br><b>{{task.title}}?</b></h2>
        <form action="" method="POST">
            <!--Note that action is empty because we are sending the request to the same page-->
            {% csrf_token %}
            <button class="button" type="submit" name="Update Task">Confirm</button>
            <a href="/" class="button">Cancel</a>
        </form>

    </div>
</body>

</html>

tasks/templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+SC:wght@100;400;700&display=swap" rel="stylesheet"> -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Cabin:ital,wght@0,400;1,600&family=Noto+Sans+SC:wght@100;400;700&display=swap" rel="stylesheet">
    <!-- <link rel="stylesheet" href="style.css"> -->
    <title>To Do App</title>
    <style>
        *,
        *::after,
        *::before {
            box-sizing: border-box;
            margin: 0;
            padding: 0;
            font-family: 'Noto Sans SC', sans-serif;
            font-weight: 400;
        }
        
         :root {
            --mainbg: rgb(241, 209, 209);
            --buttonbg: rgb(247, 152, 152);
        }
        
        html {
            font-size: 100%;
        }
        
        .container {
            display: flex;
            justify-content: center;
            flex-direction: column;
            margin: 2rem;
            /* width: 100%;
            box-sizing: border-box; */
        }
        
        .container h2 {
            font-size: 2rem;
            /* align-items: center; */
            align-self: center;
            margin-bottom: 2rem;
        }
        
        #id_title {
            display: block;
            width: 51%;
            min-width: 16rem;
            /* line-height: 4; */
            margin-bottom: 1rem;
            padding: 1rem;
            font-size: 1rem;
            background-color: var(--mainbg);
        }
        
        form {
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            color: black;
        }
        
        form button {
            cursor: pointer;
            all: unset;
            display: inline-block;
            width: 50%;
            min-width: 15rem;
            padding: 0.5rem;
            border: none;
            border-radius: 6px;
            font-size: 1rem;
            color: white;
            background-color: var(--buttonbg);
            text-decoration: none;
            text-align: center;
        }
        
        strike ul {
            text-decoration: line-through;
        }
        
        .cards {
            display: flex;
            /* flex-direction: row; */
            margin: 1rem;
            flex-wrap: wrap;
            align-items: center;
            justify-content: center;
            /* max-width: 100%; */
        }
        
        .cards ol {
            display: block;
            /* border: 2px solid red; */
            background-color: var(--mainbg);
            border-radius: 6px;
            width: 15rem;
            margin: 0.5rem 1rem;
            padding: 0.6rem;
            text-align: center;
        }
        
        .cards ol ul {
            display: inline-block;
            width: 100%;
            height: 4rem;
            margin-bottom: 0.5rem;
            text-align: center;
            word-wrap: break-word;
            /* overflow-x: scroll; */
        }
        
        .button {
            all: unset;
            display: inline-block;
            cursor: pointer;
            width: 40%;
            padding: 0.4rem 0.3rem;
            margin: 0.4rem 0.3rem;
            border-radius: 6px;
            text-decoration: none;
            background-color: var(--buttonbg);
            color: white;
        }
    </style>
</head>

<body>
    <div class="container">
        <h2>To Do List</h2>
        <form action="/" method="POST">
            {% csrf_token %} {{form.title}}
            <!--If only {{form}} would be given, all the details 
                            related to our form would show up-->
            <button type="submit" name="Create Task">Create Task</button>
            <!--These are not provided by default by the form-->
        </form>

        <div class="cards">
            {% for i in all_tasks%}
            <ol>
                {% if i.complete == True %}
                <strike>
                <ul>{{i.title}}</ul>
            </strike> {% else %}
                <ul>{{i.title}}</ul>
                {% endif %}
                <a id="update" class="button" href="update_task/{{i.id}}">Update</a>
                <a id="delete" class="button" href="delete_task/{{i.id}}">Delete</a>
                <!-- <hr> -->
            </ol>
            {% endfor %}
        </div>
    </div>

</body>

</html>

tasks/templates/update_task.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Update | To Do App</title>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Cabin:ital,wght@0,400;1,600&family=Noto+Sans+SC:wght@100;400;700&display=swap" rel="stylesheet">
    <style>
        *,
        *::after,
        *::before {
            box-sizing: border-box;
            text-decoration: none;
            margin: 0;
            padding: 0;
            font-family: 'Noto Sans SC', sans-serif;
            font-weight: 400;
        }
        
        html {
            font-size: 100%;
        }
        
         :root {
            --mainbg: rgb(241, 209, 209);
            --buttonbg: rgb(247, 152, 152);
        }
        
        .container {
            display: flex;
            justify-content: center;
            flex-direction: column;
            margin: 2rem;
        }
        
        .container h2 {
            font-size: 2rem;
            /* align-items: center; */
            align-self: center;
            margin-bottom: 2rem;
        }
        
        form {
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            color: black;
        }
        
        #id_title {
            display: block;
            width: 50%;
            /* line-height: 4; */
            margin-bottom: 1rem;
            padding: 1rem;
            font-size: 1rem;
            background-color: var(--mainbg);
        }
        
        .button {
            all: unset;
            cursor: pointer;
            display: inline-block;
            width: 8rem;
            padding: 0.4rem 0.3rem;
            margin: 0.4rem 0.3rem;
            /* border: 2px solid green; */
            border-radius: 6px;
            text-decoration: none;
            background-color: var(--buttonbg);
            color: white;
            border: none;
            text-align: center;
        }
    </style>
</head>

<body>
    <div class="container">
        <h2>Update Task</h2>
        <form action="" method="POST">
            {% csrf_token %} {{form}}
            <button class="button" type="submit" name="Update Task">Update Task</button>
        </form>
    </div>
</body>

</html>